### PR TITLE
Add virtual processing option

### PR DESCRIPTION
**Pull request by jhkennedy**
Integrates https://github.com/isce-framework/isce2/pull/319 into this plugin

### CODE REVIEW

**Comment by ehavazli** [comment]
I have been running the sample_run.sh with the newly added ```--process-virtually``` option as seen below:
```
isce2_topsapp --username <username> \
              --password <password> \
              --reference-scenes S1B_IW_SLC__1SDV_20210723T014947_20210723T015014_027915_0354B4_B3A9 \
              --secondary-scenes S1B_IW_SLC__1SDV_20210711T014922_20210711T014949_027740_034F80_859D \
                                 S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404 \
                                 S1B_IW_SLC__1SDV_20210711T015011_20210711T015038_027740_034F80_376C \
              --process-virtually \
             > topsapp_img.out 2> topsapp_img.err
```

Currently the process fails at burstifg step:
```
TopsApp Steps:  62%|██████▎   | 15/24 [3:12:49<1:55:41, 771.29s/it] 
Traceback (most recent call last):
  File "/home/havazli/miniconda3/envs/topsapp_env/bin/isce2_topsapp", line 33, in <module>
    sys.exit(load_entry_point('isce2-topsapp', 'console_scripts', 'isce2_topsapp')())
  File "/u/kriek1/havazli/DockerizedTopsApp/isce2_topsapp/__main__.py", line 117, in main
    topsapp_processing(reference_slc_zips=loc_data['ref_paths'],
  File "/u/kriek1/havazli/DockerizedTopsApp/isce2_topsapp/topsapp_proc.py", line 76, in topsapp_processing
    raise ValueError(f'TopsApp failed at step: {step}')
ValueError: TopsApp failed at step: burstifg
```

Another error I receive multiple times, which doesn't kill the process, is access to a specific dataset:

```
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw1-slc-vv-20210711t014948-20210711t015013-027740-034f80-004.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw2-slc-vv-20210711t014947-20210711t015012-027740-034f80-005.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.zip/S1B_IW_SLC__1SDV_20210711T014947_20210711T015013_027740_034F80_D404.SAFE/measurement/s1b-iw3-slc-vv-20210711t014947-20210711t015013-027740-034f80-006.tiff' does not exist in the file system, and is not recognized as a supported dataset name.
TopsApp Steps:  62%|██████▎   | 15/24 [3:08:04<4:25:35, 1770.56s/it]ERROR 4: `/vsizip/vsicurl/https://datapool.asf.alaska.edu/SLC/SB/S1B_IW_SLC__1SDV_20210723T014947_20210723T015014_027915_0354B4_B3A9.zip/S1B_IW_SLC__1SDV_20210723T014947_20210723T015014_027915_0354B4_B3A9.SAFE/measurement/s1b-iw1-slc-vv-20210723t014949-20210723t015014-027915-0354b4-004.tiff' does not exist in th
e file system, and is not recognized as a supported dataset name.

```

The process runs over 3 hours and errors out. Majority of the time is spent on fineresamp step. Fine resampling spends 5 minutes on each burst (3 subswaths X 9 bursts X 5 minutes = 2 hours 15 minutes).

My environment is a new installation of the repo and the versions of the usual suspects are:

```
  gdal                3.4.3-py310hce6f0df_0
  isce2              2.6.0-py310h13e036c_0
  python           3.10.4-h9a8a25e_0_cpython
```

**Comment by cmarshak** [comment]
@sssangha  - do you know how long fine resampling normally takes? i.e. can you get it from one of the hyp3 jobs you have submitted? That would be a helpful point of comparison. Or @ehavazli do you have this time stored elsewhere?

@ehavazli - as best as possible, as you work on this, please explain why there is so much difference between the above performance and the report below
```
We successfully included virtual data processing into ISCE2 (version 2.5.3 and above) Sentinel-1 interferogram processing, i.e. the ability for the Sentinel-1 InSAR processor to more efficiently access data in the cloud and perform initial reading completely within an instance. Our initial tests have shown ~20% increase in processing time and ~25% decrease in utilized disk space on the file system for processing collocated with the data. 
```
We are less interested in disk space right now and more just on wall-clock time.

**Comment by ehavazli** [comment]
So far I tried downgrading python and gdal packages and haven't been able to bring the virtual process to a completion. Currently I am working on locating the issue causing the virtual processing to fail at burstifg step. I believe this may be caused by a bug in the way the measurement file is called within the code.

@cmarshak The discrepancy is due to the differences in testing environments. Initial development and testing was done on OSL using 2 SLCs staged as:

```
https://jhk-data-east.s3.amazonaws.com/SLC/SA/S1A_IW_SLC__1SDV_20210501T230628_20210501T230655_037701_0472DA_54F3.zip
https://jhk-data-east.s3.amazonaws.com/SLC/SA/S1A_IW_SLC__1SDV_20210525T230629_20210525T230656_038051_047DAA_A759.zip
```

which were previously in:

```
https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20210525T230629_20210525T230656_038051_047DAA_A759.zip
https://datapool.asf.alaska.edu/SLC/SA/S1A_IW_SLC__1SDV_20210501T230628_20210501T230655_037701_0472DA_54F3.zip
```


This was done after contacting @jhkennedy and asking him to stage specific SLCs on the east coast. 

If I should look at the bigger picture here; downloading each SLC takes ~30 seconds (2.5 minutes total for the sample_run.sh) while staging virtual data files takes ~20 seconds in total. Even though the process isn't brought to a completion at the end of the virtual processing, majority of the runtime is spent on fineresample step which takes 2 hours 15 minutes. During local processing (downloading SLC's and processing on the server) fineresample step takes ~10 minutes. So we are losing way more time than we are gaining with virtual processing. I don't think the virtual processing option is a promising feature for the purpose of saving time during GUNW production. However, a fair comparison will be possible after resolving the bug which causes the virtual processing to fail.

**Comment by cmarshak** [comment]
We are going to close this until further notice because the wall-clock time is not going to improve with ISCE2 virtual data processing. At best 2% (1-2 minutes of 90+ minute processing time accounted for downloading) is the most we have to gain in wall-clock time, which has to be measured with workforce investment in making ISCE2 optimized for cloud reads (not to mention SLC data is not easily subset so may not be possible). To be clear, cannot shave all of 2% off wall-clock time, just some small fraction of it.

**Pull request closed without merging**
