### PR TITLE
Update water mask with full resolution GMT mask

### PR DESCRIPTION
**Pull request by sssangha**
Now use full res, land + ocean boundary mask uploaded to S3 by @jhkennedy.

Addresses #19

### CODE REVIEW

**Comment by cmarshak** [comment]
Can you share what the browse imagery will look like with this update particularly near a water body. Ideally the Hawaii example that @gracebato shared - https://github.com/ACCESS-Cloud-Based-InSAR/DockerizedTopsApp/pull/10#issuecomment-940374130.

Or somewhere else. Just to demonstrate to David that there is no coastline artifacts 🤞 

Thanks, Sim!

**Comment by sssangha** [comment]
@cmarshak yes no problem. It's taking a while to generate the figures for Hawaii, so in the meantime here they are for SoCal:
CA_mask_zoom
CA_mask

**Comment by sssangha** [comment]
Actually, Hawaii just finished up
Hawaii_mask
!

**Review by cmarshak — APPROVED** [review]
Beautiful!

**Comment by dbekaert** [comment]
Looks great.

Thnx

**Pull request merged**
